export enum CompanyData {
  ['Request To Receive Foreign ID'] = 'repCompanyInfo.requestToReceiveFID',
  ['Foreign Pooled'] = 'repCompanyInfo.requestToReceiveFID',
  ['Company Legal Name'] = 'names.legalName',
  ['Company Alternative Name'] = 'names.altName',
  ['Company Tax Id Type'] = 'taxInfo.taxIdType',
  ['Company Tax Id Number'] = 'taxInfo.taxIdNumber',
  ['Company Country/Jurisdiction'] = 'taxInfo.countryOrJurisdiction',
  ['Company Country/Jurisdioction of Formation'] = 'formationJurisdiction.countryOrJurisdictionOfFormation',
  ['Company Address'] = 'address.address',
  ['Company City'] = 'address.city',
  ['US or Territory'] = 'address.usOrUsTerritory',
  ['Company State'] = 'address.state',
  ['Company Zip code'] = 'address.zipCode',
}

export enum ParticipantData {
  ['IsApplicant'] = 'isApplicant',
  ['Is Existing Company'] = 'applicant.isExistingCompany',
  ['FinCEN ID'] = 'finCenId.finCENID',
  ['Last or Legal Name'] = 'personalInfo.lastOrLegalName',
  ['First Name'] = 'personalInfo.firstName',
  ['Middle Name'] = 'personalInfo.middleName',
  ['Suffix'] = 'personalInfo.suffix',
  ['Date of Birth'] = 'personalInfo.dateOfBirth',
  ['Address Type'] = 'address.type',
  ['Address'] = 'address.address',
  ['City'] = 'address.city',
  ['Country/Jurisdiction'] = 'address.countryOrJurisdiction',
  ['State'] = 'address.state',
  ['Postal Code'] = 'address.postalCode',
  ['Document Type'] = 'identificationDetails.docType',
  ['Document Number'] = 'identificationDetails.docNumber',
  ['Document Country/Jurisdiction'] = 'identificationDetails.countryOrJurisdiction',
  ['Document State'] = 'identificationDetails.state',
  ['Local or Tribal'] = 'identificationDetails.localOrTribal',
  ['Other Local or Tribal Description'] = 'identificationDetails.otherLocalOrTribalDesc',
  ['Document Image'] = 'identificationDetails.docImg',
  ['Is Parent or Guardian'] = 'beneficialOwner.isParentOrGuard',
  ['Is Exempt Entity'] = 'exemptEntity.isExemptEntity',
}
