export { CountryEnum } from './country.enum';

export enum IdentificationTypesEnum {
  EIN = 'EIN',
  SSNOrITIN = 'SSN/ITIN',
  FOREIGN = 'Foreign',
}

export enum USTerritoryEnum {
  USA = 'United States of America',
  AMERICAN_SAMOA = 'American Samoa',
  GUAM = 'Guam',
  MARSHALL_ISLANDS = 'Marshall Islands',
  MICRONESIA = 'Micaronesia, Federated States',
  NORTHERN_MARIANA_ISLANDS = 'Northern Marianna Islands',
  PALAU = 'Palau',
  PUERTO_RICO = 'Puerto Rico',
  US_VIRGIN_ISLANDS = 'U.S. Virgin Islands',
}

export enum StatesEnum {
  ALABAMA = 'Alabama',
  ALASKA = 'Alaska',
  ARMED_FORCES_EUROPE = 'Armed Forces Europe/Middle-East/Canada',
  ARMED_FORCES_AMERICA = 'Armed Forces Americas (except Canada)',
  ARMED_FORCES_PACIFIC = 'Armed Forces Pacific',
  ARIZONA = 'Arizona',
  ARKANSAS = 'Arkansas',
  CALIFORNIA = 'California',
  COLORADO = 'Colorado',
  CONNECTICUT = 'Connecticut',
  DELAWARE = 'Delaware',
  DISTRICT_OF_COLUMBIA = 'District Of Columbia',
  FLORIDA = 'Florida',
  GEORGIA = 'Georgia',
  HAWAII = 'Hawaii',
  IDAHO = 'Idaho',
  ILLINOIS = 'Illinois',
  INDIANA = 'Indiana',
  IOWA = 'Iowa',
  KANSAS = 'Kansas',
  KENTUCKY = 'Kentucky',
  LOUISIANA = 'Louisiana',
  MAINE = 'Maine',
  MARYLAND = 'Maryland',
  MASSACHUSETTS = 'Massachusetts',
  MICHIGAN = 'Michigan',
  MINNESOTA = 'Minnesota',
  MISSISSIPPI = 'Mississippi',
  MISSOURI = 'Missouri',
  MONTANA = 'Montana',
  NEBRASKA = 'Nebraska',
  NEVADA = 'Nevada',
  NEW_HAMPSHIRE = 'New Hampshire',
  NEW_JERSEY = 'New Jersey',
  NEW_MEXICO = 'New Mexico',
  NEW_YORK = 'New York',
  NORTH_CAROLINA = 'North Carolina',
  NORTH_DAKOTA = 'North Dakota',
  OHIO = 'Ohio',
  OKLAHOMA = 'Oklahoma',
  OREGON = 'Oregon',
  PENNSYLVANIA = 'Pennsylvania',
  RHODE_ISLAND = 'Rhode Island',
  SOUTH_CAROLINA = 'South Carolina',
  SOUTH_DAKOTA = 'South Dakota',
  TENNESSEE = 'Tennessee',
  TEXAS = 'Texas',
  UTAH = 'Utah',
  VERMONT = 'Vermont',
  VIRGINIA = 'Virginia',
  WASHINGTON = 'Washington',
  WEST_VIRGINIA = 'West Virginia',
  WISCONSIN = 'Wisconsin',
  WYOMING = 'Wyoming',
  AMERICAN_SAMOA = 'American Samoa',
  GUAM = 'Guam',
  NORTHERN_MARIANA_ISLANDS = 'Northern Mariana Islands',
  PUERTO_RICO = 'Puerto Rico',
  US_VIRGIN_ISLANDS = 'U.S. Virgin Islands',
}
