export enum CompanyData {
  'Request To Receive Foreign ID' = 'repCompanyInfo.requestToReceiveFID',
  'Foreign Pooled' = 'repCompanyInfo.foreignPooled',
  'Company Legal Name' = 'names.legalName',
  'Company Alternative Name' = 'names.altName',
  'Company Tax Id Type' = 'taxInfo.taxIdType',
  'Company Tax Id Number' = 'taxInfo.taxIdNumber',
  'Company Country/Jurisdiction' = 'taxInfo.countryOrJurisdiction',
  'Company Country/Jurisdiction of Formation' = 'formationJurisdiction.countryOrJurisdictionOfFormation',
  'Company Address' = 'address.address',
  'Company City' = 'address.city',
  'Company US or Territory' = 'address.usOrUsTerritory',
  'Company State' = 'address.state',
  'Company Zip code' = 'address.zipCode',
}

export enum ParticipantData {
  'Is Existing Company' = 'applicant.isExistingCompany',
  'FinCEN ID' = 'finCENID.finCENID',
  'Last or Legal Name' = 'personalInfo.lastOrLegalName',
  'First Name' = 'personalInfo.firstName',
  'Middle Name' = 'personalInfo.middleName',
  'Suffix' = 'personalInfo.suffix',
  'Date of Birth' = 'personalInfo.dateOfBirth',
  'Address Type' = 'address.type',
  'Address' = 'address.address',
  'City' = 'address.city',
  'Country/Jurisdiction' = 'address.countryOrJurisdiction',
  'State' = 'address.state',
  'Postal Code' = 'address.postalCode',
  'Document Type' = 'identificationDetails.docType',
  'Document Number' = 'identificationDetails.docNumber',
  'Document Country/Jurisdiction' = 'identificationDetails.countryOrJurisdiction',
  'Document State' = 'identificationDetails.state',
  'Local or Tribal' = 'identificationDetails.localOrTribal',
  'Other Local or Tribal Description' = 'identificationDetails.otherLocalOrTribalDesc',
  'Document Image' = 'identificationDetails.docImg',
  'Is Parent or Guardian' = 'beneficialOwner.isParentOrGuard',
  'Is Exempt Entity' = 'exemptEntity.isExemptEntity',
}

export enum UserData {
  'User Name' = 'name',
  'User Email' = 'email',
}

export const companyCSVRowDataKeys = [
  'User Name',
  'User Email',
  'Company Request To Receive Foreign ID',
  'Company Foreign Pooled',
  'Company Legal Name',
  'Company Alternative Name',
  'Company Tax Id Type',
  'Company Tax Id Number',
  'Company Country/Jurisdiction',
  'Company Country/Jurisdiction of Formation',
  'Company Address',
  'Company City',
  'Company US or Territory',
  'Company State',
  'Company Zip code',
  'Applicant Is Existing Company',
  'Applicant FinCEN ID',
  'Applicant Last or Legal Name',
  'Applicant First Name',
  'Applicant Middle Name',
  'Applicant Suffix',
  'Applicant Date of Birth',
  'Applicant Address Type',
  'Applicant Address',
  'Applicant City',
  'Applicant Country/Jurisdiction',
  'Applicant State',
  'Applicant Postal Code',
  'Applicant Document Type',
  'Applicant Document Number',
  'Applicant Document Country/Jurisdiction',
  'Applicant Document State',
  'Applicant Local or Tribal',
  'Applicant Other Local or Tribal Description',
  'Applicant Document Image',
  'Owner Is Parent or Guardian',
  'Owner Is Exempt Entity',
  'Owner FinCEN ID',
  'Owner Last or Legal Name',
  'Owner First Name',
  'Owner Middle Name',
  'Owner Suffix',
  'Owner Date of Birth',
  'Owner Address',
  'Owner City',
  'Owner Country/Jurisdiction',
  'Owner State',
  'Owner Postal Code',
  'Owner Document Type',
  'Owner Document Number',
  'Owner Document Country/Jurisdiction',
  'Owner Document State',
  'Owner Local or Tribal',
  'Owner Other Local or Tribal Description',
  'Owner Document Image',
] as const;
