export enum CompanyData {
  'Company Request To Receive Foreign ID' = 'repCompanyInfo.requestToReceiveFID',
  'Company Foreign Pooled' = 'repCompanyInfo.foreignPooled',
  'Company Legal Name' = 'names.legalName',
  'Company Alternative Name' = 'names.altName',
  'Company Tax Id Type' = 'taxInfo.taxIdType',
  'Company Tax Id Number' = 'taxInfo.taxIdNumber',
  'Company Country/Jurisdiction' = 'taxInfo.countryOrJurisdiction',
  'Company Country/Jurisdiction of Formation' = 'formationJurisdiction.countryOrJurisdictionOfFormation',
  'Company State of Formation' = 'formationJurisdiction.stateOfFormation',
  'Company Tribal Jurisdiction of Formation' = 'formationJurisdiction.tribalJurisdiction',
  'Company Name of Other Tribal' = 'formationJurisdiction.nameOfOtherTribal',
  'Company Address' = 'address.address',
  'Company City' = 'address.city',
  'Company US or Territory' = 'address.usOrUsTerritory',
  'Company State' = 'address.state',
  'Company Zip code' = 'address.zipCode',
  'Company Exists' = 'isExistingCompany',
}

export enum ParticipantData {
  'FinCEN ID' = 'finCENID.finCENID',
  'Last or Legal Name' = 'personalInfo.lastOrLegalName',
  'First Name' = 'personalInfo.firstName',
  'Middle Name' = 'personalInfo.middleName',
  'Suffix' = 'personalInfo.suffix',
  'Date of Birth' = 'personalInfo.dateOfBirth',
  'Address Type' = 'address.type',
  'Address' = 'address.address',
  'City' = 'address.city',
  'Country/Jurisdiction' = 'address.countryOrJurisdiction',
  'State' = 'address.state',
  'Postal Code' = 'address.postalCode',
  'Document Type' = 'identificationDetails.docType',
  'Document Number' = 'identificationDetails.docNumber',
  'Document Country/Jurisdiction' = 'identificationDetails.countryOrJurisdiction',
  'Document State' = 'identificationDetails.state',
  'Local or Tribal' = 'identificationDetails.localOrTribal',
  'Other Local or Tribal Description' = 'identificationDetails.otherLocalOrTribalDesc',
  'Document Image' = 'identificationDetails.docImg',
  'Is Parent or Guardian' = 'beneficialOwner.isParentOrGuard',
  'Is Exempt Entity' = 'exemptEntity.isExemptEntity',
}

export enum UserData {
  'User FirstName' = 'firstName',
  'User Email' = 'email',
  'User LastName' = 'lastName',
}
